### ISSUE TITLE
Cannot start it on PopOs 22.04

### ISSUE THREAD

**Issue by cip123** [ChristianLightServices/TimeLight#25] opened 2023-01-26 21:15 UTC
I downloaded a release Linux.package.64-bit.Qt.6.2 (I am on PopOs 22_04) and ran it, but I can't get pass by configuration. 

I chose Clockify, and I entered my API key, and then it prompted me for the workspace. 

No matter what value I enter, I can't get past that screen. 

I noticed the following warning in the console.
```
[2023-01-26 22:31:12.505] [qt] [warning] qt.tlsbackend.ossl: Incompatible version of OpenSSL (built with OpenSSL 1.x, runtime version is >= 3.x)
[2023-01-26 22:31:12.505] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:31:12.505] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
```

**Comment by LorenDB** [comment] 2023-01-26 21:20
Can you upload `~/.local/share/Christian Light/TimeLight/TimeLight.log`? That should have more detailed log output. You could also try installing `libssl3` if it is not already installed.

**Comment by cip123** [comment] 2023-01-26 21:22
```
[2023-01-26 22:09:28.445] [timelight] [trace] Starting TimeLight 2.4.1...
[2023-01-26 22:09:28.485] [timelight] [trace] Loaded API key from secret storage
[2023-01-26 22:09:28.487] [timelight] [trace] Loaded Graph access token from secret storage
[2023-01-26 22:09:28.488] [timelight] [trace] Loaded Graph refresh token from secret storage
[2023-01-26 22:09:28.492] [timelight] [trace] Initializing API key
[2023-01-26 22:10:09.539] [qt] [warning] qt.tlsbackend.ossl: Incompatible version of OpenSSL (built with OpenSSL 1.x, runtime version is >= 3.x)
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:10:09.539] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslKey
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: Active TLS backend does not support key creation
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: The backend "cert-only" does not support QSslSocket
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: The backend named "cert-only" does not support TLS
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
[2023-01-26 22:10:09.746] [network] [trace] Network request: GET https://api.clockify.me/api/v1/workspaces
[2023-01-26 22:10:09.746] [qt] [warning] qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
[2023-01-26 22:10:09.746] [timelight] [trace] Initializing workspace
[2023-01-26 22:10:18.775] [timelight] [trace] Saved API key to secret storage
[2023-01-26 22:10:18.791] [timelight] [trace] Initializing workspace
[2023-01-26 22:10:18.797] [timelight] [trace] Saved Graph access token to secret storage
[2023-01-26 22:10:18.809] [timelight] [trace] Saved Graph refresh token to secret storage
[2023-01-26 22:10:27.972] [timelight] [trace] Initializing workspace
[2023-01-26 22:10:28.468] [timelight] [trace] Initializing workspace
[2023-01-26 22:10:28.683] [timelight] [trace] Initializing workspace
[2023-01-26 22:10:28.889] [timelight] [trace] Initializing workspace
[2023-01-26 22:10:29.078] [timelight] [trace] Initializing workspace
```

**Comment by cip123** [comment] 2023-01-26 21:23
libssl3 is already installed:

```
libssl3 is already the newest version (3.0.2-0ubuntu1.7).
```

**Comment by LorenDB** [comment] 2023-01-26 21:24
OK, I will have to do some deeper debugging. I'll get back to you soon if I find anything that looks like it could be the problem.

**Comment by LorenDB** [comment] 2023-01-26 21:35
I tried running the AppImage on openSUSE and doing a fresh install in Windows Sandbox. Neither exhibited the problem.

Could you try building the app from source?

**Comment by cip123** [comment] 2023-01-26 21:37
I will try it, but I think it will be over the weekend. 

By the way, do you have any screenshots? I don't know what to expect :).

**Comment by LorenDB** [comment] 2023-01-26 22:16
I don't have any screenshots. There's not much to screenshot, as it's just a system tray icon.

**Comment by LorenDB** [comment] 2023-01-27 14:51
OK, I just spun up a Pop!_OS VM. It looks like this is caused by the fact that Ubuntu has stopped packaging libssl 1.1 in favor of libssl 3 (which is a good thing). However, it seems that the AppImages are being linked to libssl 1.1, meaning that HTTPS traffic fails, meaning that once you have input the API key, TimeLight is unable to communicate with the Clockify API. I will look for a fix.

**Comment by LorenDB** [comment] 2023-01-27 15:52
I'm not finding a good fix right off the bat. For now, I'd say work around this either by building from source or by [installing libssl1.1](https://stackoverflow.com/a/73346208/12533859). If you do build from source, be prepared to hunt down a number of packages that may need installed.

**Comment by cip123** [comment] 2023-01-27 21:57
OK, installing `libssl1.1` worked.  Thanks a lot. 
If somebody else needs it, here is the link.  

```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
```

**Comment by LorenDB** [comment] 2023-01-30 20:29
I'm going to close this for now as I'm afraid that this is not an easily fixable issue at the moment. I'll pin this issue in case other people have the same question.

**Closed by LorenDB** 2023-01-30 20:29 UTC

**Comment by cip123** [comment] 2023-02-01 14:48
I wanted to mention that I have the same issue with Arch.

**Comment by LorenDB** [comment] 2023-02-01 15:45
True, anybody with no libssl1 in their distro will be affected.

**Comment by wu-lee** [comment] 2024-03-08 12:02
Same issue here on Kubuntu 22.04 LTS. Lucky I saw the pinned issue, would have been a bit clueless otherwise and so probably would have given up and moved on. 

The installation steps described above allow me to successfully authenticate and show the list of workspaces, and therefore get past the set-up step.
 
Possibly worth a mention on the main project page?
